import type { Metadata } from 'next';
import './globals.css';
import Script from 'next/script';
import Link from 'next/link';
import Header from '@/components/Header';
import Footer from '@/components/Footer';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`h-full antialiased`}>
      <head>
        {/* reCAPTCHA Enterprise Script */}
        <Script src="https://www.google.com/recaptcha/enterprise.js?render=6LcyBpAsAAAAAO6OUHgkuJMpmxKerDgmu2Ff0TuH"></Script>
      </head>
      <body className="min-h-full flex flex-col">
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}

